Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 1, artist: "Abba", song: "Dancing Queen"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 2, artist: "Abba", song: "Gimme!"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 98, artist: "Ace of Base", song: "All that she wants"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 3, artist: "AC/DC", song: "Highway to Hell"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 119, artist: "a-ha", song: "Take on me"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 125, artist: "Alanis Morissette", song: "Ironic"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 124, artist: "Alice Cooper", song: "Poison"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 136, artist: "Amy Winehouse", song: "Valerie"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 128, artist: "Aretha Franklin", song: "I say a little prayer for you"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 126, artist: "Aretha Franklin", song: "Respect"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 4, artist: "Arvingarna", song: "Eloise"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 121, artist: "Avicii", song: "Hey Brother"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 5, artist: "Backstreet Boys", song: "As long as you love me"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 96, artist: "Belinda Carlisle", song: "Heaven is a place on earth"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 108, artist: "Bert", song: "Älskade Ängel"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 7, artist: "Beyonce", song: "Crazy in love"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 8, artist: "Beyonce", song: "Halo"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 73, artist: "Beyonce", song: "Love on top"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 109, artist: "Björn Skifs", song: "Hooked on a feeling"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 6, artist: "Björn Skifs", song: "Michelangelo"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 88, artist: "Bon Jovi", song: "Livin on a prayer"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 9, artist: "Bonnie Tyler", song: "Total eclipse of the heart"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 140, artist: "Bonnie Tyler", song: "Holding out for a hero"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 105, artist: "Boston", song: "More than a feeling"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 10, artist: "Britney Spears", song: "Baby one more time"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 71, artist: "Britney Spears", song: "Ooops I did it again"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 11, artist: "Broder Daniel", song: "Shoreline"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 123, artist: "Bryan Adams", song: "Summer of ’69"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 12, artist: "Carola", song: "Fångad av en stormvind"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 72, artist: "Carola", song: "Främling"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 92, artist: "Carola", song: "Mickey"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 107, artist: "Charlotte Perelli", song: "Tusen och en natt"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 78, artist: "Cher", song: "If I could turn back time"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 134, artist: "Chicago", song: "You’re the inspiration"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 79, artist: "Cindy Lauper", song: "Girls just wanna have fun"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 13, artist: "Coldplay", song: "Fix You"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 14, artist: "Daft Punk", song: "Get Lucky"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 15, artist: "Destinys Child", song: "Say my name"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 135, artist: "Dolly Parton", song: "Here you come again"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 74, artist: "Dolly Parton", song: "9 to 5"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 95, artist: "Donna Summer", song: "Hot Stuff"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 16, artist: "Dusty Springfield", song: "Son of a preacherman"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 17, artist: "Earth, Wind & Fire", song: "September"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 76, artist: "Elvis Presley", song: "Hound dog"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 90, artist: "Eva Dahlgren", song: "Jag klär av mig"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 112, artist: "4 Non Blondes", song: "What’s up?"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 127, artist: "First Aid Kit", song: "Emmylou"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 18, artist: "GES", song: "När vi gräver guld i USA"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 19, artist: "Gloria Gaynor", song: "I will survive"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 82, artist: "Grease", song: "You’re the one that I want"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 20, artist: "Hanson", song: "MMMBop"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 110, artist: "Helen Sjöholm", song: "Du måste finnas"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 106, artist: "Hello Saferide", song: "Get Sick Soon"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 21, artist: "Herreys", song: "Diggiloo Diggiley"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 102, artist: "Hot Chocolate", song: "You Sexy Thing"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 22, artist: "Håkan Hellström", song: "En midsommarnattsdröm"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 23, artist: "Håkan Hellström", song: "Ramlar"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 24, artist: "Håkan Hellström", song: "Kom igen Lena!"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 25, artist: "Håkan Hellström", song: "Känn ingen sorg för mig Göteborg"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 26, artist: "Huey Lewis & The News", song: "Hip to be square"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 94, artist: "Irene Cara", song: "What a feeling"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 62, artist: "Jackson 5", song: "Blame it on the boogie"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 63, artist: "Jackson 5", song: "I want you back"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 64, artist: "Jackson 5", song: "ABC"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 101, artist: "James Brown", song: "I Feel Good"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 120, artist: "Janis Joplin", song: "Me and Bobby McGee"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 27, artist: "Janne Lucas", song: "Växeln Hallå"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 28, artist: "Journey", song: "Don’t stop believin’"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 29, artist: "Justin Timberlake", song: "Can’t stop the feeling"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 30, artist: "Kenny Rogers", song: "Islands in the stream"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 89, artist: "Kikki Danielsson", song: "Bra vibrationer"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 31, artist: "Kings of Leon", song: "Sex on fire"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 137, artist: "Lady Gaga/Bradley Cooper", song: "Shallow"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 84, artist: "Laleh", song: "En stund på jorden"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 32, artist: "Lena Philipsson", song: "Dansa i neon"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 33, artist: "Lena Philipsson", song: "Kärleken är evig"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 34, artist: "Linnea Henriksson", song: "Du söker bråk, jag kräver dans"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 143, artist: "Lisa Ekdahl", song: "Vem vet?"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 100, artist: "Lisa Nilsson", song: "Himlen runt hörnet"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 113, artist: "Lisa Nilsson", song: "Varje gång jag ser dig"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 35, artist: "Madonna", song: "Like a prayer"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 93, artist: "Madonna", song: "Like a virgin"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 138, artist: "Markoolio/Linda Bengtzing", song: "Värsta schlagern"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 36, artist: "Mark Ronson/Bruno Mars", song: "Uptown Funk"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 37, artist: "Marvin Gaye", song: "Ain’t no mountain"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 103, artist: "Marvin Gaye", song: "Sexual Healing"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 133, artist: "Mauro Scocco", song: "Sarah"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 38, artist: "Michael Jackson", song: "Billie Jean"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 39, artist: "Michael Jackson", song: "P.Y.T"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 86, artist: "Michael Sembello", song: "Maniac"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 139, artist: "Moulin Rouge", song: "Come what may"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 130, artist: "Nanne Grönvall", song: "Avundsjuk"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 40, artist: "Oskar Linnros", song: "Från och med du"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 114, artist: "Petra Marklund", song: "Händerna mot himlen"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 41, artist: "Pharell", song: "Happy"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 42, artist: "Queen", song: "Don’t stop me now"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 132, artist: "Queen", song: "Somebody to love"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 43, artist: "Ramones", song: "Blietzkrieg Bop"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 44, artist: "Rihanna", song: "Umbrella"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 45, artist: "Robbie Williams", song: "Let me entertain you"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 46, artist: "Robyn", song: "Dancing on my own"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 47, artist: "Robyn", song: "Be mine"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 81, artist: "Roger Pontare", song: "När vindarna viskar mitt namn"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 97, artist: "Roxette", song: "The look"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 141, artist: "Sam Brown", song: "Stop!"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 111, artist: "Sarek", song: "Genom Eld och vatten"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 75, artist: "Simon & Garfunkel", song: "Bridge over troubled waters"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 77, artist: "Spice Girls", song: "2 become 1"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 48, artist: "Spice Girls", song: "Wannabe"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 49, artist: "StevieWonder", song: "I wish"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 50, artist: "Stevie Wonder", song: "Signed, sealed, delievered"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 51, artist: "Stevie Wonder", song: "Superstition"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 131, artist: "Survivor", song: "Eye of the tiger"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 52, artist: "Ted Gärdestad", song: "Satellit"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 53, artist: "Ted Gärdestad", song: "Jag ska fånga en ängel"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 54, artist: "The Ark", song: "Calleth You, cometh I"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 55, artist: "The Ark", song: "It takes a fool to remain sane"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 104, artist: "The Beach Boys", song: "God Only Knows"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 118, artist: "The Beatles", song: "Hey Jude"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 129, artist: "The Cardigans", song: "Lovefool"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 56, artist: "The Commitments", song: "Mustang Sally"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 122, artist: "The Cranberries", song: "Zombie"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 80, artist: "The Pointer Sisters", song: "I’m so excited"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 57, artist: "The Proclaimers", song: "I’m gonna be (500 miles)"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 58, artist: "The Rolling Stones", song: "Satisfaction"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 59, artist: "The Rolling Stones", song: "Start me up"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 60, artist: "The Kinks", song: "You really got me"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 99, artist: "Weather Girls", song: "It’s raining men"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 117, artist: "Tomas Ledin", song: "Hon gör allt för att göra mig lycklig"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 61, artist: "Tomas Ledin", song: "Inatt är jag din"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 87, artist: "Tom Jones", song: "It’s not unusual"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 115, artist: "Tom Jones", song: "Delilah"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 83, artist: "Tommy Körberg", song: "Stad i ljus"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 142, artist: "Towa Carson", song: "Alla har glömt"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 65, artist: "TinaTurner", song: "The best"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 91, artist: "Tina Turner", song: "What’s love got to do with it"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 66, artist: "Van Halen", song: "Jump"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 67, artist: "Veronica Maggio", song: "Jag kommer"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 85, artist: "Village People", song: "YMCA"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 68, artist: "Whitney Houston", song: "How will I know"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 69, artist: "Whitney Houston", song: "I wanna dance with somebody"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 116, artist: "Whitney Houston", song: "I Will always love you"})
Karroake.Repo.insert!(%Karroake.KaraokeList.Song{id: 70, artist: "Zara Larsson", song: "Lush Life"})
